name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.3.0

      - name: Install Nix
        uses: cachix/install-nix-action@v31.5.0

      - name: Build
        run: nix-shell --run "make"

      - name: Run tests
        run: nix-shell --run "./test/test.sh"

  bench:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.3.0

      - name: Install Nix
        uses: cachix/install-nix-action@v31.5.0

      - name: Build
        run: nix-shell --run "make bench"

      - name: Run bench
        run: nix-shell --run "./bench/bench.sh" >> "$GITHUB_STEP_SUMMARY"

      - name: Run bench regression
        if: github.event_name == 'pull_request'
        run: nix-shell --run "./bench/bench_regression.sh master build/csv_demo.o" >> "$GITHUB_STEP_SUMMARY"

  style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.3.0

      - name: Install Nix
        uses: cachix/install-nix-action@v31.5.0

      - name: Build
        run: nix-shell --run "make style-check"
